language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "RbjjJUm5fzmiN1s+qAB3IG2bDaIJPuYvjdgWssO5jETUFMDfuSQNtkJMjgaHrfeh4XHnIhgKhb5z4Oj8YQbJkTU97vlsVN0Oegb1UZFDMuekwU9zbywi7HfIPzViOzcckWmwSLjoQwnTOK9+yjkFCFUSz6I8YSYGrgbr9myk072rGDt5HHU4khB9oclH497mvCNBB4FRg/qR8C37hxRjmy90C92Sha1ugB2SVdk9HZ5altTHujfVxa1kdYV239QdC3ALvwbxj/FdxOwMJsOxqWPJQOXo/x+ozrJuiTIcWWWZtxHI7IWeA1ciJNQQaCpxGrMiGcoL+TAsLYm7QCNHvNE8rwvx4hNd6l5FKU8y6+MEEdkVtqyP/0mCWLPXMb3d12aHGqtqbr8CfVlBxzcYojHwt6bh8tcPliwMT6MJPMxXpP2+aWviLyI+LroUV0I01HbZkUYNb7DPrvZeU2GUqou+4XJIvR7zuJSr4zffn2anC/Lu53rp5PFQ+koRjYkbbtBrOevV1riwP5J4q6kRRPgza/GXMlOTofcK+TGjnZXyxuf4A4V1OEI8pAdBCfnwTCOAJEDMuvtNGC2uLEPsZifn72HNY1nHj94euDB+86gikzQOM6lMDLXN4lWE1QztCzpSTjNxPXrTSOlITCW3w4cQypCfXf7YzDH8iXa+Udo="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
