language: php
sudo: false

php:
    - 7.4

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "cxeFigZLrvghVpoqfEIYwoEtJRNIcUeVfapZDW9KO4ZXkUJswuHBtU30pTKbjUP6xCV4LuLu5TH+lLkzkmLsbJElAeISmFIGD6OoaMjcw0w94eG+XO24N60LYHd6L/qeNHXyi69g42dja+lWYnpXhsn3gAmJMf7SQHbavviz5Z5FpceiBnONqxuMTyyXxCTVOG3MWrgnuLNZ9BJFE+QlaKMkA8g18MYAsbCQRkzQmPU3YWNzTwGAHld53dUw7KVH3Y9azp7vnbpZrm7c1VT4lJobUW46T5mla9HrpAqqVjDL8yS5YFOYrg96dKCVwL0m2vwW6xkdrWjO+qmZwzqeVPHknAYDbmk20Hsycaahou1ip3qWKLbL9my21SKtkDaYLpjjeFe2uIVDmm7VlIXm3xCetaYc3XSBY3Am0jhFMj67FwY2DwErTQAsZZRrIio+gusLQ2cmkmLTlW9ilpHYTaS0D1i+hzi7MbJCW4k8tKhnfm1NUJs+f6DmxFOzDeNucpsZ1PQbgUkg7qpJvPqgH1thRaAtT0OCQMdcjjb3wyM0KS8VVLwApz4no/FQAp9OMopH0XwjaGSkoNzwvgLs4hHwR4c9v0McHDBOorEo3b1JNBuqO6/tFB5sEPDA0hH2DhA9BU6q/RJG8XGGmG/67UZ+1ryqP/7gR1BLZy0dQ8w="

git:
    depth: false

install: composer update --no-interaction --no-suggest --no-progress

script:
    - phpdbg -qrr vendor/bin/phpunit  --coverage-clover phpunit.coverage.xml --log-junit phpunit.report.xml
    - sonar-scanner
