language: php
sudo: false
php:
    - 8.0
cache:
    directories:
        - $HOME/.composer/cache
addons:
    sonarcloud:
        organization: "quillstack"
        token:
            secure: "GTkK0+4yveEXNS3XYg8140n7iJ6zEYROInvDtwBl/TBRPo1E9poCXJqIuiId3dGcuPWJ9TLFoKJlVrMF6jI4qzYv4IL2ednmzk/6/eJPewmJQ3B8fDly5DdENbdDA5npgyqLKfoal/N961+cZ11oftvzCBmflRNXcMvL7jfT1rZoN+QE7yvLU/pk6bLTgkUQHME0DZDnOTI0T8zaN1J2f2oSH8/zwAsGIVI645bXn7+4MQ6ZBiGgeVuoH4+BtDb/iJ6OV3baFGQpTomknAs+GUcuzf+OaIBH04EgsS9T9GbuGwn7lI0U7DgbcGfmGj1et2s5ullY7ANQrze304uOnI7ZKWxVBf2Eq0PaurslBucmMjtFzN3b4WCWMFdnx9GrDib4oeqJKBjhfRLE84vt3Kx+jdfnm1z9JlEhuorHlU1wjugEXHUCQNcvSJZDXJ/Mc69ptknVgRtn+0JmoDUJbdkkmbAyvbaTZBtItT1CTDDlgebmvrh3uJnPT30OL8ksCna8tSYPW0zkTzyIbKDeliOjoYTYaBjm6hRgJi+7lACMRxP4lQaOamc7Kf6TYi2A2LdHSNfUrxAP63xI3zZFV5jtfOkCMynO4CfiP5/l/KmuSQyqiNVQoXLfPhy9VElnIJ7+fVi8kFrzWgs1HrQqg+p/PaKykehnkfoO3r0QiAE="
git:
    depth: false
install: composer update --no-interaction --no-suggest --no-progress
script:
    - phpdbg -qrr ./vendor/bin/unit-tests
    - sonar-scanner
